// Module2_FrontendDev/Abisha Eunice/handson_06/student-portal-react/src/components/CourseCard.jsx
import { useDispatch } from "react-redux";
import { enroll } from "../redux/enrollmentSlice";
import { useNavigate } from "react-router-dom";

function CourseCard({ id, name, code, credits, grade }) {

    const dispatch = useDispatch();
    const navigate = useNavigate();

    const handleEnroll = () => {
        dispatch(
            enroll({
                id,
                name,
                code,
                credits,
                grade
            })
        );

        navigate("/profile");
    };

    return (
        <article className="course-card">

            <h3>{name}</h3>

            <p>Code: {code}</p>

            <p>Credits: {credits}</p>

            <p>Grade: {grade}</p>

            <button onClick={() => navigate(`/courses/${id}`)}>
                View Details
            </button>

            <button onClick={handleEnroll}>
                Enroll
            </button>

        </article>
    );
}

export default CourseCard;

// Module2_FrontendDev/Abisha Eunice/handson_08/student-portal-vue/src/components/CourseCard.vue
<script setup>


defineProps({

name:String,

code:String,

credits:Number,

grade:String

})


</script>



<template>


<div class="card">


<h3>
{{name}}
</h3>


<p>
Code: {{code}}
</p>


<p>
Credits: {{credits}}
</p>


<p>
Grade: {{grade}}
</p>


<button @click="$emit('enroll')">

Enroll

</button>


<button @click="$router.push('/courses/'+code)">

View Details

</button>


</div>


</template>



<style scoped>

.card{

background:white;

padding:20px;

border-radius:10px;

box-shadow:0 2px 8px #ccc;

}


button{

margin:5px;

padding:8px;

cursor:pointer;

}

</style>
